// "Campaign focus" cards — 2-3 short themes drawn from this month's plan,
// generated by DeepSeek (Alan's standing choice over Claude for this
// codebase's classification/generation tasks — see spam-classify.ts) at the
// moment the plan is saved, not on every page render. That keeps this to
// one cheap call per client per month, hung off an action Alan already
// takes, rather than a new thing to operate. See D54.
const DEEPSEEK_BASE = "https://api.deepseek.com";
const MODEL = "deepseek-chat";

const SYSTEM_PROMPT = `You write short "campaign focus" cards for a home-services marketing client portal. Given this month's plan (a list of things the agency is doing for the client) and recent completed work, produce 2-3 short themes explaining what the plan is FOR — the underlying goal each action serves, not a restatement of the actions themselves.

Each theme needs: a single emoji icon, a 2-4 word title, and a one-sentence explanation a non-technical small-business owner would find reassuring and clear. No jargon, no vague marketing language ("synergy", "leverage", "optimize").

Respond with ONLY a JSON array, no other text, 2 to 3 items:
[{"icon": "📈", "title": "Grow visibility", "body": "..."}]`;

export type FocusItem = { icon: string; title: string; body: string };

export async function generateFocus(input: {
  clientName: string;
  planItems: string[];
  recentWork: string[];
}): Promise<FocusItem[]> {
  const apiKey = process.env.DEEPSEEK_API_KEY;
  if (!apiKey) throw new Error("DEEPSEEK_API_KEY not configured");

  if (input.planItems.length === 0) return [];

  const res = await fetch(`${DEEPSEEK_BASE}/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 400,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: JSON.stringify({
            client: input.clientName,
            thisMonthsPlan: input.planItems,
            recentlyCompleted: input.recentWork,
          }),
        },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`DeepSeek generateFocus failed: ${res.status} ${body}`);
  }

  const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  const text = json.choices?.[0]?.message?.content ?? "[]";

  // DeepSeek's JSON mode wants an object at the top level, so the prompt
  // above asks for an array but the API may wrap it — handle both shapes
  // rather than trusting the model to violate its own JSON-mode contract.
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    return [];
  }
  const arr = Array.isArray(parsed)
    ? parsed
    : Array.isArray((parsed as Record<string, unknown>)?.items)
      ? (parsed as { items: unknown[] }).items
      : Object.values(parsed as Record<string, unknown>).find((v) => Array.isArray(v));

  if (!Array.isArray(arr)) return [];

  return arr
    .filter(
      (i): i is FocusItem =>
        typeof i === "object" &&
        i !== null &&
        typeof (i as FocusItem).icon === "string" &&
        typeof (i as FocusItem).title === "string" &&
        typeof (i as FocusItem).body === "string",
    )
    .slice(0, 3);
}
